[theme]
base = "light"
primaryColor = "#d0adc6"
backgroundColor = "#E8EEF9"
secondaryBackgroundColor = "#BFE0F5"
textColor = "#062e5d"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = "full"

[logger]
# Forzamos a Streamlit a estar en nivel DEBUG o INFO para capturar todo
level = "debug"
messageFormat = "%(asctime)s %(message)s"
